
export const SET_CREATE_TASK = "SET_CREATE_TASK";


export const LOGOUT = "LOGOUT";

export const GET_AUTH = "GET_AUTH";
export const GET_AUTH_REQUEST = "GET_AUTH_REQUEST";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
export const GET_AUTH_FAILED = "GET_AUTH_FAILED";

export const POST_AUTH = "POST_AUTH"
export const POST_AUTH_REQUEST = "POST_AUTH_REQUEST"
export const POST_AUTH_SUCCESS = "POST_AUTH_SUCCESS"
export const POST_AUTH_FAILED = "POST_AUTH_FAILED"

export const POST_USER = "POST_USER";
export const POST_USER_REQUEST = "POST_USER_REQUEST";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const POST_USER_FAILED = "POST_USER_FAILED";


export const GET_SKILLS = "GET_SKILLS";
export const GET_SKILLS_REQUEST = "GET_SKILLS_REQUEST";
export const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";
export const GET_SKILLS_FAILED = "GET_SKILLS_FAILED";

export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_REQUEST = "GET_LANGUAGES_REQUEST";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_FAILED = "GET_LANGUAGES_FAILED";


export const GET_CITIES = "GET_CITIES";
export const GET_CITIES_REQUEST = "GET_CITIES_REQUEST";
export const GET_CITIES_FAILED = "GET_CITIES_FAILED";
export const GET_CITIES_SUCCESS = "GET_CITIES_SUCCESS";

export const GET_TASKS = "GET_TASKS"
export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST"
export const GET_TASKS_FAILED = "GET_TASKS_FAILED"
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS"

export const GET_TASK = "GET_TASK"
export const GET_TASK_REQUEST = "GET_TASK_REQUEST"
export const GET_TASK_FAILED = "GET_TASK_FAILED"
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS"

export const GET_CATEGORIES_GROUPS_REQUEST = "GET_CATEGORIES_GROUPS_REQUEST"
export const GET_CATEGORIES_GROUPS_SUCCESS = "GET_CATEGORIES_GROUPS_SUCCESS"
export const GET_CATEGORIES_GROUPS_FAILED = "GET_CATEGORIES_GROUPS_FAILED"

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED"

export const UPDATE_AUTH_PROFILE = "UPDATE_AUTH_PROFILE"

export const PATCH_USER_REQUEST = "PATCH_USER_REQUEST"
export const PATCH_USER_SUCCESS = "PATCH_USER_SUCCESS"
export const PATCH_USER_FAILED = "PATCH_USER_FAILED"

export const POST_TASKER_REQUEST = "POST_TASKER_REQUEST"
export const POST_TASKER_SUCCESS = "POST_TASKER_SUCCESS"
export const POST_TASKER_FAILED = "POST_TASKER_FAILED"

export const POST_TASKS_REQUEST = "POST_TASKS_REQUEST";
export const POST_TASKS_FAILED = "POST_TASKS_FAILED";
export const POST_TASKS_SUCCESS = "POST_TASKS_SUCCESS";

export const POST_OFFERS_REQUEST = "POST_OFFERS_REQUEST";
export const POST_OFFERS_FAILED = "POST_OFFERS_FAILED";
export const POST_OFFERS_SUCCESS = "POST_OFFERS_SUCCESS";

export const GET_MY_ACTIVE_TASKS_REQUEST = "GET_MY_ACTIVE_TASKS_REQUEST";
export const GET_MY_ACTIVE_TASKS_FAILED = "GET_MY_ACTIVE_TASKS_FAILED";
export const GET_MY_ACTIVE_TASKS_SUCCESS = "GET_MY_ACTIVE_TASKS_SUCCESS";

export const GET_ACTIVE_LISTING_REQUEST = "GET_ACTIVE_LISTING_REQUEST";
export const GET_ACTIVE_LISTING_FAILED = "GET_ACTIVE_LISTING_FAILED";
export const GET_ACTIVE_LISTING_SUCCESS = "GET_ACTIVE_LISTING_SUCCESS";

export const GET_ACTIVE_LISTING2_REQUEST = "GET_ACTIVE_LISTING2_REQUEST";
export const GET_ACTIVE_LISTING2_FAILED = "GET_ACTIVE_LISTING2_FAILED";
export const GET_ACTIVE_LISTING2_SUCCESS = "GET_ACTIVE_LISTING2_SUCCESS";

export const GET_ACTIVE_LISTING3_REQUEST = "GET_ACTIVE_LISTING3_REQUEST";
export const GET_ACTIVE_LISTING3_FAILED = "GET_ACTIVE_LISTING3_FAILED";
export const GET_ACTIVE_LISTING3_SUCCESS = "GET_ACTIVE_LISTING3_SUCCESS";

export const GET_TASKS_COUNT_REQUEST = "GET_TASKS_COUNT_REQUEST";
export const GET_TASKS_COUNTS_FAILED = "GET_TASKS_COUNTS_FAILED";
export const GET_TASKS_COUNT_SUCCESS = "GET_TASKS_COUNT_SUCCESS";

export const UPDATE_AUTH_PROFILE_TASKER = "UPDATE_AUTH_PROFILE_TASKER";

export const PATCH_TASKS_SUCCESS = "PATCH_TASKS_SUCCESS";

export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_FAILED = "UPDATE_TASK_FAILED";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_FAILED = "GET_USER_FAILED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_OFFER_REQUEST = "GET_OFFER_REQUEST";
export const GET_OFFER_FAILED = "GET_OFFER_FAILED";
export const GET_OFFER_SUCCESS = "GET_OFFER_SUCCESS";

export const ACCEPT_OFFER_REQUEST = "ACCEPT_OFFER_REQUEST";
export const ACCEPT_OFFER_FAILED = "ACCEPT_OFFER_FAILED";
export const ACCEPT_OFFER_SUCCESS = "ACCEPT_OFFER_SUCCESS";

export const GET_MY_ACTIVE_OFFERS_REQUEST = "GET_MY_ACTIVE_OFFERS_REQUEST";
export const GET_MY_ACTIVE_OFFERS_FAILED = "GET_MY_ACTIVE_OFFERS_FAILED";
export const GET_MY_ACTIVE_OFFERS_SUCCESS = "GET_MY_ACTIVE_OFFERS_SUCCESS";

export const GET_OFFERS_REQUEST = "GET_OFFERS_REQUEST";
export const GET_OFFERS_FAILED = "GET_OFFERS_FAILED";
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";

export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_FAILED = "GET_MESSAGES_FAILED";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";

export const POST_MESSAGES_REQUEST = "POST_MESSAGES_REQUEST";
export const POST_MESSAGES_FAILED = "POST_MESSAGES_FAILED";
export const POST_MESSAGES_SUCCESS = "POST_MESSAGES_SUCCESS";

export const SEND_VERIFICATION_CODE_REQUEST = "SEND_VERIFICATION_CODE_REQUEST";
export const SEND_VERIFICATION_CODE_FAILED = "SEND_VERIFICATION_CODE_FAILED";
export const SEND_VERIFICATION_CODE_SUCCESS = "SEND_VERIFICATION_CODE_SUCCESS";

export const VALIDATE_VERIFICATION_CODE_REQUEST = "VALIDATE_VERIFICATION_CODE_REQUEST";
export const VALIDATE_VERIFICATION_CODE_FAILED = "VALIDATE_VERIFICATION_CODE_FAILED";
export const VALIDATE_VERIFICATION_CODE_SUCCESS = "VALIDATE_VERIFICATION_CODE_SUCCESS";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_FAILED = "GET_POSTS_FAILED";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const POST_POSTS_REQUEST = "POST_POSTS_REQUEST";
export const POST_POSTS_FAILED = "POST_POSTS_FAILED";
export const POST_POSTS_SUCCESS = "POST_POSTS_SUCCESS";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_FAILED = "GET_POST_FAILED";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";

export const PATCH_POSTS_REQUEST = "PATCH_POSTS_REQUEST";
export const PATCH_POSTS_FAILED = "PATCH_POSTS_FAILED";
export const PATCH_POSTS_SUCCESS = "PATCH_POSTS_SUCCESS";

export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS";
